import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getEvacuationCenters } from '../../api/evacuation';
import { useAuthStore } from '../../store/authStore';
import { formatDateTime } from '../../utils/floodUtils';
import { FileDown, TrendingUp, Users, Home, X } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '../../api/axios';

export default function MswdoReports() {
  const { user } = useAuthStore();
  const [selectedCenterId, setSelectedCenterId] = useState(user?.evacuation_center_id ? String(user.evacuation_center_id) : '');

  const [pdfPreview, setPdfPreview] = useState(null);
  const [filterGender, setFilterGender] = useState('');
  const [filterAgeMin, setFilterAgeMin] = useState('');
  const [filterAgeMax, setFilterAgeMax] = useState('');

  const { data: centers = [] } = useQuery({
    queryKey: ['evacuation'],
    queryFn: getEvacuationCenters,
  });

  // Effective selected center ID (defaults to user's assigned center or first available center)
  const activeCenterId = selectedCenterId || (user?.evacuation_center_id ? String(user.evacuation_center_id) : (centers[0] ? String(centers[0].id) : 'all'));

  // All evacuees across all centers
  const { data: allFamilies = [] } = useQuery({
    queryKey: ['all-families'],
    queryFn: () => api.get('/evacuation/all-families').then(r => r.data.data || []).catch(async () => {
      if (!centers.length) return [];
      const results = await Promise.all(
        centers.map(c => api.get(`/evacuation/${c.id}/families`).then(r => (r.data.data || []).map(f => ({ ...f, center_name: c.name }))))
      );
      return results.flat();
    }),
    enabled: centers.length > 0,
  });

  const isAll = activeCenterId === 'all';
  const selectedCenter = centers.find(c => String(c.id) === String(activeCenterId));

  const centerName = isAll ? 'All Evacuation Centers' : (selectedCenter?.name || '—');
  const centerBarangay = isAll ? 'All Barangays' : (selectedCenter?.barangay_name || selectedCenter?.barangay || '—');

  const families = isAll
    ? allFamilies
    : allFamilies.filter(f => String(f.evacuation_center_id) === String(activeCenterId));

  const familyEvacueeCount = families.reduce((s, f) => s + (Number(f.members) || 0), 0);

  const current = isAll
    ? Math.max(allFamilies.reduce((s, f) => s + (Number(f.members) || 0), 0), centers.reduce((s, c) => s + (Number(c.capacity_current) || 0), 0))
    : Math.max(Number(selectedCenter?.capacity_current) || 0, familyEvacueeCount);

  const total = isAll
    ? (centers.reduce((s, c) => s + (Number(c.capacity_total) || 0), 0) || 1)
    : (Number(selectedCenter?.capacity_total) || 1);

  const avail = Math.max(total - current, 0);
  const rawPct = total > 0 ? (current / total) * 100 : 0;
  const pct = Math.min(rawPct, 100);
  const pctFormatted = pct === 0 ? '0%' : pct < 1 ? `${pct.toFixed(1)}%` : `${Math.round(pct)}%`;

  const totalMembers = families.reduce((s, f) => s + (Number(f.members) || 0), 0);

  const filteredAll = useMemo(() => {
    return families.filter(f => {
      if (filterGender && f.gender !== filterGender) return false;
      const age = f.age ? parseInt(f.age) : null;
      if (filterAgeMin && (age === null || age < parseInt(filterAgeMin))) return false;
      if (filterAgeMax && (age === null || age > parseInt(filterAgeMax))) return false;
      return true;
    });
  }, [families, filterGender, filterAgeMin, filterAgeMax]);

  const exportCenterPDF = () => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const nowStr = new Date().toLocaleString('en-PH', { dateStyle: 'long', timeStyle: 'short' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('MSWDO — Evacuee & Occupancy Report', 14, 16);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Evacuation Center: ${centerName}`, 14, 23);
    doc.text(`Barangay: ${centerBarangay}`, 14, 29);
    doc.text(`Generated: ${nowStr}`, 14, 35);
    doc.text(`Generated by: ${user?.full_name || '—'} (${user?.role || 'MSWDO Officer'})`, 14, 41);
    doc.text(`Total Registered Families: ${families.length}   Total Members: ${totalMembers}`, 14, 47);

    // Summary Table
    autoTable(doc, {
      startY: 52,
      head: [['Current Evacuees', 'Max Capacity', 'Available Space', 'Occupancy Rate', 'Registered Families', 'Total Members', 'Center Status']],
      body: [
        [current, total, avail, pctFormatted, families.length, totalMembers, isAll ? 'N/A' : (selectedCenter?.is_open ? 'Open' : 'Closed')]
      ],
      styles: { fontSize: 9, cellPadding: 3, halign: 'center' },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [241, 245, 249] },
    });

    const summaryEndY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : 70;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Family Records & Individual Members', 14, summaryEndY);

    if (families.length > 0) {
      autoTable(doc, {
        startY: summaryEndY + 4,
        head: [['#', 'Head of Family', 'Age', 'Gender', 'Address', 'Barangay', 'Center', 'Members', 'Contact', 'Arrival Date', 'Family Members List']],
        body: families.map((f, i) => [
          i + 1,
          f.head_name || '—',
          f.age || '—',
          f.gender || '—',
          f.address || '—',
          f.barangay || '—',
          f.center_name || '—',
          f.members,
          f.contact || '—',
          f.arrival_date ? new Date(f.arrival_date).toLocaleDateString('en-PH') : '—',
          f.members_list?.length
            ? f.members_list.map((m, mi) => `${mi + 1}. ${m.name}${m.age ? ` (${m.age})` : ''}${m.gender ? ` [${m.gender}]` : ''}`).join('\n')
            : '—',
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [241, 245, 249] },
        columnStyles: { 0: { cellWidth: 8 }, 7: { cellWidth: 16 }, 10: { cellWidth: 55 } },
      });
    } else {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(150);
      doc.text('No family records available for this center.', 14, summaryEndY + 8);
    }

    const filename = `evacuees_${centerName.replace(/\s+/g, '_').toLowerCase()}.pdf`;
    setPdfPreview({ url: doc.output('bloburl'), filename });
  };

  const stats = [
    { icon: Users, label: 'Current Evacuees', value: current, color: '#2563eb' },
    { icon: Home, label: 'Max Capacity', value: total, color: '#7c3aed' },
    { icon: TrendingUp, label: 'Occupancy Rate', value: pctFormatted, color: pct >= 75 ? '#dc2626' : '#16a34a' },
    { icon: Users, label: 'Registered Families', value: families.length, color: '#d97706' },
  ];

  return (
    <div className="space-y-6">
      <div className="page-header flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports</h1>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-slate-600 dark:text-slate-400 text-sm font-semibold">Center:</span>
            <select
              value={activeCenterId}
              onChange={e => setSelectedCenterId(e.target.value)}
              className="bg-white border border-slate-300 dark:bg-slate-800 dark:border-slate-700 text-slate-900 dark:text-white text-sm font-semibold rounded-xl px-3 py-1.5 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-sm"
            >
              <option value="all">All Evacuation Centers</option>
              {centers.map(c => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          </div>
        </div>
        <button onClick={exportCenterPDF}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-bold px-4 py-2.5 rounded-xl transition-colors shadow-sm">
          <FileDown size={15} /> Export PDF Report
        </button>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map(({ icon: Icon, label, value, color }) => (
          <div key={label} className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <Icon size={16} style={{ color }} />
              <span className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider">{label}</span>
            </div>
            <div className="text-3xl font-black" style={{ color }}>{value}</div>
          </div>
        ))}
      </div>

      {/* Occupancy bar */}
      <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm">
        <div className="flex items-center justify-between mb-3">
          <span className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">Capacity Utilization</span>
          <span className="text-xs font-semibold text-slate-600 dark:text-slate-400">{current} / {total}</span>
        </div>
        <div className="h-5 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden mb-2">
          <div className="h-full rounded-full transition-all duration-500 flex items-center justify-end pr-2"
            style={{ width: `${Math.max(pct, current > 0 ? 2 : 0)}%`, backgroundColor: pct >= 100 ? '#ef4444' : pct >= 75 ? '#f59e0b' : '#22c55e' }}>
            {pct > 15 && <span className="text-xs font-bold text-white">{pctFormatted}</span>}
          </div>
        </div>
        <div className="flex justify-between text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">
          <span>0 occupants</span><span>{total} max</span>
        </div>
      </div>

      {/* PDF Preview Modal */}
      {pdfPreview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
          <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 rounded-2xl w-full max-w-4xl flex flex-col shadow-2xl" style={{ height: '90vh' }}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-slate-700 shrink-0">
              <span className="text-sm font-bold text-slate-900 dark:text-white">PDF Preview — {pdfPreview.filename}</span>
              <div className="flex items-center gap-2">
                <a href={pdfPreview.url} download={pdfPreview.filename}
                  className="flex items-center gap-1.5 text-xs bg-blue-600 hover:bg-blue-500 text-white px-3 py-1.5 rounded-lg transition-colors font-bold shadow-sm">
                  <FileDown size={13} /> Download
                </a>
                <button onClick={() => setPdfPreview(null)} className="text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white transition-colors p-1">
                  <X size={18} />
                </button>
              </div>
            </div>
            <iframe key={pdfPreview.url} src={pdfPreview.url} className="flex-1 w-full rounded-b-2xl" title="PDF Preview" />
          </div>
        </div>
      )}

      {/* All Evacuee Data */}
      <div>
        <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
          <h2 className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
            Evacuee Data ({isAll ? 'All Centers' : centerName})
          </h2>
          <div className="flex items-center gap-2 flex-wrap">
            <select value={filterGender} onChange={e => setFilterGender(e.target.value)}
              className="bg-white border border-slate-300 text-slate-900 dark:bg-slate-700 dark:border-slate-600 dark:text-white text-xs font-semibold rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-sm">
              <option value="">All Genders</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
            <input type="number" min="0" max="120" placeholder="Age min" value={filterAgeMin}
              onChange={e => setFilterAgeMin(e.target.value)}
              className="w-20 bg-white border border-slate-300 text-slate-900 dark:bg-slate-700 dark:border-slate-600 dark:text-white text-xs font-semibold rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-sm" />
            <input type="number" min="0" max="120" placeholder="Age max" value={filterAgeMax}
              onChange={e => setFilterAgeMax(e.target.value)}
              className="w-20 bg-white border border-slate-300 text-slate-900 dark:bg-slate-700 dark:border-slate-600 dark:text-white text-xs font-semibold rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-sm" />
            {(filterGender || filterAgeMin || filterAgeMax) && (
              <button onClick={() => { setFilterGender(''); setFilterAgeMin(''); setFilterAgeMax(''); }}
                className="text-xs font-bold text-slate-700 hover:text-slate-900 bg-slate-200 hover:bg-slate-300 dark:text-slate-300 dark:hover:text-white px-2.5 py-1.5 dark:bg-slate-700 rounded-lg transition-colors shadow-sm">Clear</button>
            )}
            <span className="text-xs font-semibold text-slate-600 dark:text-slate-400 bg-slate-100 dark:bg-slate-700/50 px-2 py-1 rounded-full">{filteredAll.length} records</span>
          </div>
        </div>
        <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl overflow-hidden shadow-sm">
          {filteredAll.length === 0 ? (
            <div className="flex items-center justify-center py-12 text-slate-500 text-sm font-semibold">
              <Users size={28} className="mr-2 opacity-30" /> No evacuee records
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
                    {['#', 'Head of Family', 'Age', 'Gender', 'Barangay', 'Members', 'Contact', 'Arrival Date', 'Center', 'Notes'].map(h => (
                      <th key={h} className="px-4 py-3 text-left text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider whitespace-nowrap">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200 dark:divide-slate-700/50">
                  {filteredAll.map((f, i) => (
                    <tr key={f.id} className="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors">
                      <td className="px-4 py-3 text-slate-500 text-xs font-medium">{i + 1}</td>
                      <td className="px-4 py-3 font-bold text-slate-900 dark:text-white">{f.head_name}</td>
                      <td className="px-4 py-3 text-slate-700 dark:text-slate-300 font-medium">{f.age || '—'}</td>
                      <td className="px-4 py-3 text-slate-700 dark:text-slate-300 font-medium">{f.gender || '—'}</td>
                      <td className="px-4 py-3 text-slate-700 dark:text-slate-300 font-medium">{f.barangay || '—'}</td>
                      <td className="px-4 py-3 text-blue-600 dark:text-blue-400 font-bold">{f.members}</td>
                      <td className="px-4 py-3 text-slate-700 dark:text-slate-300 font-mono font-medium">{f.contact || '—'}</td>
                      <td className="px-4 py-3 text-slate-500 dark:text-slate-400 text-xs whitespace-nowrap font-medium">
                        {f.arrival_date ? new Date(f.arrival_date).toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' }) : '—'}
                      </td>
                      <td className="px-4 py-3 text-slate-700 dark:text-slate-300 text-xs font-semibold">{f.center_name || '—'}</td>
                      <td className="px-4 py-3 text-slate-500 dark:text-slate-400 text-xs max-w-[140px] truncate font-medium">{f.notes || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* Family records summary table */}
      <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl overflow-hidden shadow-sm">
        <div className="px-5 py-4 border-b border-slate-200 dark:border-slate-700">
          <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">Family Records Summary</h3>
          <p className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-0.5">{families.length} families · {totalMembers} total members</p>
        </div>
        {families.length === 0 ? (
          <div className="flex items-center justify-center py-12 text-slate-500 text-sm font-semibold">No family records yet</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
                  {['Head of Family', 'Barangay', 'Center', 'Members', 'Contact', 'Registered'].map(h => (
                    <th key={h} className="px-5 py-3 text-left text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-700/50">
                {families.map(f => (
                  <tr key={f.id} className="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors">
                    <td className="px-5 py-3 font-bold text-slate-900 dark:text-white">{f.head_name}</td>
                    <td className="px-5 py-3 text-slate-700 dark:text-slate-300 font-medium">{f.barangay || '—'}</td>
                    <td className="px-5 py-3 text-slate-700 dark:text-slate-300 text-xs font-semibold">{f.center_name || '—'}</td>
                    <td className="px-5 py-3 text-blue-600 dark:text-blue-400 font-bold">{f.members}</td>
                    <td className="px-5 py-3 text-slate-700 dark:text-slate-300 font-mono font-medium">{f.contact || '—'}</td>
                    <td className="px-5 py-3 text-slate-500 dark:text-slate-400 text-xs font-medium">{formatDateTime(f.created_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
